---
title: "Untitled"
author: "pritom"
date: "9/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
df <- read_csv("000webhost_Extracted_PINs.csv")
```

```{r}
x <- 
    expand_grid(firstTwo = 0:99,
            lastTwo = 0:99) %>%
    full_join(
        df %>%
            filter(nchar(CommonPINs) == 4) %>%
            mutate(
                CommonPINs = as.numeric(CommonPINs),
                firstTwo = CommonPINs %/% 100,
                lastTwo = CommonPINs %% 100
            ) %>%
            count(firstTwo, lastTwo) %>%
            na.omit(),
        by = c("firstTwo", "lastTwo")
    ) %>%
    mutate(n = ifelse(is.na(n), 1, n + 1),
           n = n / sum(n),
           n = -log2(n)) %>%
    ggplot(aes(firstTwo, lastTwo, fill = n)) +
    geom_rect(aes(
        xmin = firstTwo - .5,
        xmax = firstTwo + .5,
        ymin = lastTwo - .5,
        ymax = lastTwo + .5
    )) +
    scale_fill_gradient(
        latex2exp::TeX("-log_2(PIN)"),
        low = "blue",
        high = "white",
        breaks = 4:18
    ) +
    theme_bw() +
    labs(x = "First two PIN disits", y = "Second two PIN disits") +
    scale_x_continuous(
        breaks = seq(0, 99, 5),
        minor_breaks = 0:99,
        labels = c("00", "05", seq(10, 99, 5)),
        expand = c(.005, .005)
    ) +
    scale_y_continuous(
        breaks = seq(0, 99, 5),
        minor_breaks = 0:99,
        labels = c("00", "05", seq(10, 99, 5)),
        expand = c(.007, .007)
    ) +
    theme(
        legend.title = element_text(angle = 90),
        panel.grid.minor = element_line(colour = "gray", size = .5)
    ) 
    
# ggsave(plot = x,
#         filename = "dataset1.png",
#         width = 10,
#        height = 6,
#         device = "png",
#         dpi = 1700
#     )

ggplotly(x)
```




















